import { NextResponse } from "next/server"

export async function GET() {
  // Simulated data source status for all remaining tools
  const remainingSiteStatus = {
    timestamp: new Date().toISOString(),
    tools: {
      "Index Trend Analysis & Forecast": [
        {
          indicator: "Price Data (Daily OHLCV)",
          primary: "Twelve Data API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "Twelve Data API",
        },
        {
          indicator: "Moving Averages (20, 50, 200-day)",
          primary: "Twelve Data API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "Twelve Data API",
        },
        {
          indicator: "RSI (Relative Strength Index)",
          primary: "Twelve Data API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "Twelve Data API",
        },
        {
          indicator: "Volume Data",
          primary: "Twelve Data API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "Twelve Data API",
        },
      ],
      "Fear & Greed Index": [
        {
          indicator: "VIX (CBOE Volatility Index)",
          primary: "Alpha Vantage API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "Alpha Vantage API",
        },
        {
          indicator: "Put/Call Ratio",
          primary: "BarChart API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "BarChart API",
        },
        {
          indicator: "Market Momentum (S&P 500 vs 125-day MA)",
          primary: "Twelve Data API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "Twelve Data API",
        },
        {
          indicator: "Junk Bond Demand (HYG vs LQD)",
          primary: "Alpha Vantage API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "Alpha Vantage API",
        },
        {
          indicator: "Safe Haven Demand (Stocks vs Bonds)",
          primary: "Twelve Data API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "ai",
          currentSource: "Anthropic Claude",
        },
        {
          indicator: "Stock Price Breadth (52-week highs/lows)",
          primary: "Finnhub API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "ai",
          currentSource: "OpenAI GPT-4o",
        },
        {
          indicator: "Stock Price Strength (S&P 500 above 200-day MA)",
          primary: "Twelve Data API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "Twelve Data API",
        },
      ],
      "Panic/Euphoria Index": [
        {
          indicator: "VIX Z-Score",
          primary: "Alpha Vantage API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "Alpha Vantage API",
        },
        {
          indicator: "High Yield Spread Z-Score",
          primary: "FRED API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "FRED API",
        },
        {
          indicator: "Equity Fund Flows Z-Score",
          primary: "OpenAI GPT-4o",
          fallback1: "Anthropic Claude",
          fallback2: "Groq Llama",
          fallback3: "Grok xAI",
          fallback4: "Historical Baseline",
          status: "ai",
          currentSource: "OpenAI GPT-4o",
        },
        {
          indicator: "Earnings Revisions Z-Score",
          primary: "FMP API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "FMP API",
        },
        {
          indicator: "GDP Growth Z-Score",
          primary: "FRED API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "FRED API",
        },
        {
          indicator: "Credit Spread Z-Score",
          primary: "FRED API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "FRED API",
        },
        {
          indicator: "Commodity Prices Z-Score",
          primary: "Alpha Vantage API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "ai",
          currentSource: "Groq Llama",
        },
        {
          indicator: "Currency Volatility Z-Score",
          primary: "Twelve Data API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "Twelve Data API",
        },
        {
          indicator: "Market Breadth Z-Score",
          primary: "Finnhub API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "ai",
          currentSource: "Anthropic Claude",
        },
      ],
      "VIX Volatility Index": [
        {
          indicator: "Current VIX Level",
          primary: "Alpha Vantage API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "Alpha Vantage API",
        },
        {
          indicator: "VIX Historical Average",
          primary: "Alpha Vantage API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Historical Baseline",
          status: "live",
          currentSource: "Alpha Vantage API",
        },
        {
          indicator: "VIX Percentile (1-year)",
          primary: "Alpha Vantage API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Historical Baseline",
          status: "live",
          currentSource: "Alpha Vantage API",
        },
      ],
      "Fed Rate Analysis & Forecast": [
        {
          indicator: "Fed Funds Futures Prices",
          primary: "FRED API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "FRED API",
        },
        {
          indicator: "Current Fed Funds Rate",
          primary: "FRED API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "FRED API",
        },
        {
          indicator: "FOMC Meeting Dates",
          primary: "Federal Reserve Website",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Historical Baseline",
          status: "ai",
          currentSource: "OpenAI GPT-4o",
        },
      ],
      "CPI Inflation Analysis & Forecast": [
        {
          indicator: "Monthly CPI (Headline)",
          primary: "FRED API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "FRED API",
        },
        {
          indicator: "Core CPI (Ex Food & Energy)",
          primary: "FRED API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "FRED API",
        },
        {
          indicator: "3-Month CPI Trend",
          primary: "FRED API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Historical Baseline",
          status: "live",
          currentSource: "FRED API",
        },
        {
          indicator: "12-Month CPI Change (YoY)",
          primary: "FRED API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "FRED API",
        },
      ],
      "Earnings EM Calculator": [
        {
          indicator: "Current Stock Price",
          primary: "Twelve Data API",
          fallback1: "Alpha Vantage API",
          fallback2: "Finnhub API",
          fallback3: "OpenAI GPT-4o",
          fallback4: "Anthropic Claude",
          status: "live",
          currentSource: "Twelve Data API",
        },
        {
          indicator: "Implied Volatility (ATM Options)",
          primary: "Polygon API",
          fallback1: "Twelve Data API",
          fallback2: "OpenAI GPT-4o",
          fallback3: "Anthropic Claude",
          fallback4: "Historical Baseline",
          status: "live",
          currentSource: "Polygon API",
        },
        {
          indicator: "Days to Earnings",
          primary: "FMP API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Groq Llama",
          fallback4: "Grok xAI",
          status: "live",
          currentSource: "FMP API",
        },
        {
          indicator: "Historical Earnings Moves (4 quarters avg)",
          primary: "FMP API",
          fallback1: "OpenAI GPT-4o",
          fallback2: "Anthropic Claude",
          fallback3: "Historical Baseline",
          fallback4: "Grok xAI",
          status: "ai",
          currentSource: "Anthropic Claude",
        },
      ],
      "Greeks Calculator": [
        {
          indicator: "Stock Price",
          primary: "Twelve Data API",
          fallback1: "Alpha Vantage API",
          fallback2: "Finnhub API",
          fallback3: "OpenAI GPT-4o",
          fallback4: "User Input",
          status: "live",
          currentSource: "Twelve Data API",
        },
        {
          indicator: "Strike Price",
          primary: "User Input",
          fallback1: "N/A",
          fallback2: "",
          fallback3: "",
          fallback4: "",
          status: "live",
          currentSource: "User Input",
        },
        {
          indicator: "Days to Expiration (DTE)",
          primary: "User Input",
          fallback1: "N/A",
          fallback2: "",
          fallback3: "",
          fallback4: "",
          status: "live",
          currentSource: "User Input",
        },
        {
          indicator: "Implied Volatility",
          primary: "Polygon API",
          fallback1: "Twelve Data API",
          fallback2: "OpenAI GPT-4o",
          fallback3: "Historical Average",
          fallback4: "User Input",
          status: "live",
          currentSource: "Polygon API",
        },
        {
          indicator: "Risk-Free Rate (10Y Treasury)",
          primary: "FRED API",
          fallback1: "Alpha Vantage API",
          fallback2: "OpenAI GPT-4o",
          fallback3: "Historical Baseline",
          fallback4: "User Input",
          status: "live",
          currentSource: "FRED API",
        },
        {
          indicator: "Dividend Yield",
          primary: "FMP API",
          fallback1: "Alpha Vantage API",
          fallback2: "OpenAI GPT-4o",
          fallback3: "User Input",
          fallback4: "Zero Default",
          status: "live",
          currentSource: "FMP API",
        },
      ],
      "ROI Calculator": [
        {
          indicator: "Premium Received",
          primary: "User Input",
          fallback1: "N/A",
          fallback2: "",
          fallback3: "",
          fallback4: "",
          status: "live",
          currentSource: "User Input",
        },
        {
          indicator: "Capital at Risk (Strike × 100)",
          primary: "User Input",
          fallback1: "N/A",
          fallback2: "",
          fallback3: "",
          fallback4: "",
          status: "live",
          currentSource: "User Input",
        },
        {
          indicator: "Days to Expiration",
          primary: "User Input",
          fallback1: "N/A",
          fallback2: "",
          fallback3: "",
          fallback4: "",
          status: "live",
          currentSource: "User Input",
        },
      ],
      "Put Selling Scanner": [
        {
          indicator: "Stock Universe (Top 500 by volume)",
          primary: "Polygon API",
          fallback1: "Twelve Data API",
          fallback2: "Finnhub API",
          fallback3: "OpenAI GPT-4o",
          fallback4: "Anthropic Claude",
          status: "live",
          currentSource: "Polygon API",
        },
        {
          indicator: "Option Premium & Greeks",
          primary: "Polygon API",
          fallback1: "Twelve Data API",
          fallback2: "OpenAI GPT-4o",
          fallback3: "Historical Baseline",
          fallback4: "Failed",
          status: "live",
          currentSource: "Polygon API",
        },
        {
          indicator: "IV Rank (52-week)",
          primary: "Polygon API",
          fallback1: "Twelve Data API",
          fallback2: "OpenAI GPT-4o",
          fallback3: "Historical Baseline",
          fallback4: "Failed",
          status: "live",
          currentSource: "Polygon API",
        },
        {
          indicator: "Technical Analysis (Price vs MA)",
          primary: "Twelve Data API",
          fallback1: "Alpha Vantage API",
          fallback2: "OpenAI GPT-4o",
          fallback3: "Anthropic Claude",
          fallback4: "Groq Llama",
          status: "live",
          currentSource: "Twelve Data API",
        },
        {
          indicator: "PE Ratio",
          primary: "FMP API",
          fallback1: "Alpha Vantage API",
          fallback2: "OpenAI GPT-4o",
          fallback3: "Anthropic Claude",
          fallback4: "Failed",
          status: "live",
          currentSource: "FMP API",
        },
        {
          indicator: "Revenue Growth",
          primary: "FMP API",
          fallback1: "Alpha Vantage API",
          fallback2: "OpenAI GPT-4o",
          fallback3: "Anthropic Claude",
          fallback4: "Failed",
          status: "ai",
          currentSource: "OpenAI GPT-4o",
        },
        {
          indicator: "Debt-to-Equity Ratio",
          primary: "FMP API",
          fallback1: "Alpha Vantage API",
          fallback2: "OpenAI GPT-4o",
          fallback3: "Anthropic Claude",
          fallback4: "Failed",
          status: "ai",
          currentSource: "Anthropic Claude",
        },
      ],
    },
  }

  return NextResponse.json(remainingSiteStatus)
}
