-- 0017 — declare `members` and `password_resets`, which were never in migrations.
--
-- These two tables have existed in production since the private-club work
-- (2026-08-27, commits 5704feb and 5972a94) and were created outside the
-- migration history. Everything else the app reads is declared here; these two
-- were not, which means **this folder was not the schema of record**. A fresh
-- deploy built from these migrations would have come up without the members
-- table and the login for everyone except the owner would fail.
--
-- Found on 2026-08-31 by scripts/check-postgrest-columns.ts, which validates
-- every PostgREST `select=` against the declared schema. It reported these two
-- tables as undeclared while chasing an unrelated column-name bug — the check
-- was written for one defect and immediately found another.
--
-- WRITTEN FROM THE LIVE SCHEMA, not from memory: column names, types,
-- nullability and defaults were read back out of information_schema on the
-- production project before this file was written. `if not exists` throughout,
-- so applying it to the existing database is a no-op and applying it to a fresh
-- one reproduces what production actually has.

create table if not exists public.members (
  id            bigint generated by default as identity primary key,
  email         text        not null unique,
  password_hash text        not null,
  active        boolean     not null default true,
  created_at    timestamptz not null default now(),
  last_login_at timestamptz
);

comment on table public.members is
  'Private-club members. The owner authenticates against ADMIN_EMAIL/ADMIN_PASSWORD in the environment and does NOT have a row here; a member session carries role "member" and is refused by every /api/admin route (lib/auth.ts isAdmin / verifyAuth).';

create table if not exists public.password_resets (
  id         bigint generated by default as identity primary key,
  member_id  bigint      not null references public.members (id) on delete cascade,
  -- The token is stored HASHED. A reset table holding usable tokens is a
  -- second password store with a shorter lifetime.
  token_hash text        not null,
  expires_at timestamptz not null,
  used_at    timestamptz,
  created_at timestamptz not null default now()
);

-- Reset lookup is by token hash, and expiry/used are checked on every attempt.
create index if not exists password_resets_token_hash_idx on public.password_resets (token_hash);
create index if not exists password_resets_member_idx on public.password_resets (member_id, created_at desc);
