-- 0018 — Ticker Research Queue (RESEARCH_QUEUE_DESIGN.md, Phase 1).
--
-- Keyed by OWNER EMAIL, not member_id. The owner (admin) authenticates against
-- ADMIN_EMAIL and has NO row in `members`, so a member_id FK would exclude the
-- primary user. Both admin and member sessions carry an email
-- (lib/auth.ts getSessionInfo), so email is the identity that covers both.
--
-- RLS enabled with no policies = deny-all except the service-role key, the
-- house pattern (every other table). All access is server-side via
-- SUPABASE_SERVICE_ROLE_KEY.

create table if not exists public.research_queue (
  id                  bigint generated by default as identity primary key,
  owner_email         text        not null,
  ticker              text        not null,
  status              text        not null default 'pending',
  -- Position context, so "we hold shares — sell calls or exit?" is answerable.
  shares_held         integer     not null default 0,
  cost_basis          numeric,
  -- The OptionsRecommendation (see lib/research/types.ts), null until researched.
  recommendation      jsonb,
  -- The prior recommendation, so the nightly recap (Phase 3) can diff "what
  -- changed" without a second table.
  prev_recommendation jsonb,
  researched_at       timestamptz,
  created_at          timestamptz not null default now(),
  -- One row per (owner, ticker): re-adding an existing ticker updates it rather
  -- than duplicating the queue.
  unique (owner_email, ticker)
);

alter table public.research_queue enable row level security;

create index if not exists research_queue_owner_idx
  on public.research_queue (owner_email, created_at desc);

comment on table public.research_queue is
  'Per-owner ticker research queue. status: pending|researching|researched|failed|stale|paused|archived. Keyed by session email (admin has no members row). recommendation holds the computed OptionsRecommendation; prev_recommendation feeds the morning recap diff.';

-- Per-owner wheel profile (ported from TradingAgents wheel_profile). One row per
-- owner; sensible defaults so research works before anyone edits it.
create table if not exists public.wheel_profile (
  owner_email                 text        primary key,
  account_type                text        not null default 'taxable',   -- 401k | taxable | ira
  willing_to_be_assigned      boolean     not null default true,
  avoid_earnings_within_dte   boolean     not null default true,
  max_capital_per_trade_usd   numeric     not null default 25000,
  min_iv_rank_for_premium_sale numeric    not null default 30,          -- 0..100
  target_csp_delta_low        numeric     not null default 0.16,        -- ~84% POP
  target_csp_delta_high       numeric     not null default 0.30,
  preferred_dte_low           integer     not null default 30,
  preferred_dte_high          integer     not null default 45,
  leaps_min_dte               integer     not null default 365,
  leaps_target_delta_low      numeric     not null default 0.70,
  leaps_target_delta_high     numeric     not null default 0.80,
  updated_at                  timestamptz not null default now()
);

alter table public.wheel_profile enable row level security;

comment on table public.wheel_profile is
  'Per-owner premium-selling preferences (ported from TradingAgents wheel_profile, Apache-2.0). Drives strike-by-delta, DTE, IV-rank gate and capital sizing in the research job.';
