import { NextResponse } from "next/server"

export async function GET() {
  const dataSourceStatus = {
    timestamp: new Date().toISOString(),
    summary: {
      total: 15,
      live: 8,
      aiFallback: 7,
      baseline: 0,
      failed: 0,
    },
    sources: [
      {
        name: "QQQ Technicals",
        pillar: "Momentum & Technical",
        primarySource: "Twelve Data API",
        fallbackChain: ["Grok xAI", "Groq Llama", "Anthropic Claude", "OpenAI GPT-4o"],
        currentSource: "Twelve Data API",
        status: "live",
        statusLabel: "Live API Data",
        color: "green",
      },
      {
        name: "VIX Term Structure",
        pillar: "Risk Appetite & Volatility",
        primarySource: "Alpha Vantage API",
        fallbackChain: ["Grok xAI", "Groq Llama", "Anthropic Claude", "OpenAI GPT-4o"],
        currentSource: "Alpha Vantage API",
        status: "live",
        statusLabel: "Live API Data",
        color: "green",
      },
      {
        name: "FRED Macro",
        pillar: "Macro Economic",
        primarySource: "FRED API",
        fallbackChain: ["Grok xAI", "Groq Llama", "Anthropic Claude", "OpenAI GPT-4o"],
        currentSource: "FRED API",
        details: "Fed Funds, Yield Curve, M2",
        status: "live",
        statusLabel: "Live API Data",
        color: "green",
      },
      {
        name: "Fear & Greed Index",
        pillar: "Risk Appetite & Volatility",
        primarySource: "CNN API",
        fallbackChain: ["Grok xAI", "Groq Llama", "Anthropic Claude", "OpenAI GPT-4o"],
        currentSource: "CNN API",
        status: "live",
        statusLabel: "Live API Data",
        color: "green",
      },
      {
        name: "Buffett Indicator",
        pillar: "Valuation & Market Structure",
        primarySource: "Grok xAI (AI)",
        fallbackChain: ["Groq Llama", "Anthropic Claude", "OpenAI GPT-4o", "Historical baseline"],
        currentSource: "Grok xAI",
        status: "aiFallback",
        statusLabel: "AI-Fetched Data",
        color: "yellow",
      },
      {
        name: "AAII Sentiment",
        pillar: "Risk Appetite & Volatility",
        primarySource: "ScrapingBee",
        fallbackChain: ["Grok xAI", "Groq Llama", "Anthropic Claude", "OpenAI GPT-4o"],
        currentSource: "Grok xAI",
        status: "aiFallback",
        statusLabel: "AI-Fetched Data",
        color: "yellow",
      },
      {
        name: "Put/Call Ratio",
        pillar: "Risk Appetite & Volatility",
        primarySource: "BarChart",
        fallbackChain: ["Grok xAI", "Groq Llama", "Anthropic Claude", "OpenAI GPT-4o"],
        currentSource: "BarChart",
        status: "live",
        statusLabel: "Live API Data",
        color: "green",
      },
      {
        name: "Short Interest",
        pillar: "Risk Appetite & Volatility",
        primarySource: "Finviz / Alpha Vantage",
        fallbackChain: ["Grok xAI", "Groq Llama", "Anthropic Claude", "OpenAI GPT-4o"],
        currentSource: "Grok xAI",
        status: "aiFallback",
        statusLabel: "AI-Fetched Data",
        color: "yellow",
      },
      {
        name: "QQQ Forward P/E",
        pillar: "Valuation & Market Structure",
        primarySource: "Apify Yahoo Finance",
        fallbackChain: ["Grok xAI", "Groq Llama", "Anthropic Claude", "OpenAI GPT-4o"],
        currentSource: "Apify Yahoo Finance",
        status: "live",
        statusLabel: "Live API Data",
        color: "green",
      },
      {
        name: "Mag7 Concentration",
        pillar: "Valuation & Market Structure",
        primarySource: "Grok xAI (AI)",
        fallbackChain: ["Groq Llama", "Anthropic Claude", "OpenAI GPT-4o"],
        currentSource: "Grok xAI",
        status: "aiFallback",
        statusLabel: "AI-Calculated Data",
        color: "yellow",
      },
      {
        name: "Shiller CAPE",
        pillar: "Valuation & Market Structure",
        primarySource: "FRED API",
        fallbackChain: ["Grok xAI", "Groq Llama", "Anthropic Claude", "OpenAI GPT-4o"],
        currentSource: "Grok xAI",
        status: "aiFallback",
        statusLabel: "AI-Fetched Data",
        color: "yellow",
      },
      {
        name: "S&P 500 P/E",
        pillar: "Valuation & Market Structure",
        primarySource: "FMP API",
        fallbackChain: ["Grok xAI", "Groq Llama", "Anthropic Claude", "OpenAI GPT-4o"],
        currentSource: "FMP API",
        status: "live",
        statusLabel: "Live API Data",
        color: "green",
      },
      {
        name: "ISM Manufacturing PMI",
        pillar: "Macro Economic",
        primarySource: "Grok xAI (AI)",
        fallbackChain: ["Groq Llama", "Anthropic Claude", "OpenAI GPT-4o"],
        currentSource: "Grok xAI",
        status: "aiFallback",
        statusLabel: "AI-Fetched Data",
        color: "yellow",
      },
      {
        name: "NVIDIA Momentum",
        pillar: "Momentum & Technical",
        primarySource: "Alpha Vantage",
        fallbackChain: ["Grok xAI", "Groq Llama", "Anthropic Claude", "OpenAI GPT-4o"],
        currentSource: "Alpha Vantage",
        status: "live",
        statusLabel: "Live API Data",
        color: "green",
      },
      {
        name: "SOX Semiconductor",
        pillar: "Momentum & Technical",
        primarySource: "Alpha Vantage",
        fallbackChain: ["Grok xAI", "Groq Llama", "Anthropic Claude", "OpenAI GPT-4o"],
        currentSource: "Grok xAI",
        status: "aiFallback",
        statusLabel: "AI-Fetched Data",
        color: "yellow",
      },
    ],
  }

  return NextResponse.json(dataSourceStatus)
}
