// Universe lists and slider tier tables for the Sell Put (Wheel) Scanner.
// Extracted verbatim from components/wheel-scanner.tsx (Phase 4 modularization — zero behavior change).

// TODO(S-7): the MEGA_CAP universes below are currently unused by the scanner
// flow (Step 2 loads its ticker universe from /api/polygon-tickers). Kept
// pending the S-7 universe-source decision — do not delete until S-7 is resolved.
export const MEGA_CAP_STOCKS = [
  // Mega-cap Tech (Top tier - all $100B+ market cap)
  "AAPL",
  "MSFT",
  "GOOGL",
  "AMZN",
  "NVDA",
  "META",
  "TSLA",
  "AVGO",
  "ORCL",
  "ADBE",
  "CRM",
  "AMD",
  "INTC",
  "CSCO",
  "QCOM",
  "NFLX",
  "TXN",
  "AMAT",
  "INTU",
  "NOW",

  // Major Financials (All $50B+ market cap)
  "BRK.B",
  "JPM",
  "V",
  "MA",
  "BAC",
  "WFC",
  "GS",
  "MS",
  "C",
  "AXP",
  "SPGI",
  "BLK",
  "SCHW",
  "CB",
  "PGR",
  "MMC",
  "ICE",
  "COF",
  "USB",
  "TFC",

  // Healthcare & Pharma (All $50B+ market cap)
  "UNH",
  "LLY",
  "JNJ",
  "ABBV",
  "MRK",
  "TMO",
  "ABT",
  "DHR",
  "PFE",
  "BMY",
  "AMGN",
  "GILD",
  "CVS",
  "CI",
  "ELV",
  "HUM",
  "ISRG",
  "REGN",
  "VRTX",
  "SYK",

  // Consumer & Retail (All $50B+ market cap)
  "WMT",
  "COST",
  "HD",
  "MCD",
  "NKE",
  "LOW",
  "SBUX",
  "TGT",
  "TJX",
  "BKNG",
  "PG",
  "KO",
  "PEP",
  "PM",
  "MO",
  "MDLZ",
  "CL",
  "EL",
  "MNST",
  "KHC",

  // Industrials & Materials (All $30B+ market cap)
  "CAT",
  "BA",
  "GE",
  "HON",
  "UNP",
  "RTX",
  "LMT",
  "DE",
  "UPS",
  "ADP",
  "MMM",
  "EMR",
  "ITW",
  "ETN",
  "PH",
  "GD",
  "NOC",
  "FDX",
  "CSX",
  "NSC",

  // Energy (All $50B+ market cap)
  "XOM",
  "CVX",
  "COP",
  "SLB",
  "EOG",
  "MPC",
  "PSX",
  "VLO",
  "OXY",
  "HAL",

  // Communication Services (All $20B+ market cap)
  "T",
  "VZ",
  "TMUS",
  "CMCSA",
  "DIS",
  "CHTR",
  "EA",
  "NWSA",
  "FOXA",
  "WBD",

  // Utilities & Other
  "NEE",
  "DUK",
  "SO",
  "D",
  "AEP",
  "EXC",
  "SRE",
  "PEG",
  "XEL",
  "ED",
]

export const MEGA_CAP_STOCKS_ALPHABETIZED = [
  "AAPL",
  "ABT",
  "ABBV",
  "ADBE",
  "ADP",
  "AEP",
  "AMAT",
  "AMD",
  "AMGN",
  "AMZN",
  "AVGO",
  "AXP",
  "BA",
  "BAC",
  "BKNG",
  "BLK",
  "BMY",
  "BRK.B",
  "C",
  "CAT",
  "CB",
  "CHTR",
  "CI",
  "CL",
  "CMCSA",
  "COF",
  "COP",
  "COST",
  "CRM",
  "CSCO",
  "CSX",
  "CVS",
  "CVX",
  "D",
  "DE",
  "DHR",
  "DIS",
  "DUK",
  "EA",
  "ED",
  "EL",
  "ELV",
  "EMR",
  "EOG",
  "ETN",
  "EXC",
  "FDX",
  "FOXA",
  "GD",
  "GE",
  "GILD",
  "GOOGL",
  "GS",
  "HAL",
  "HD",
  "HON",
  "HUM",
  "ICE",
  "INTC",
  "INTU",
  "ISRG",
  "ITW",
  "JNJ",
  "JPM",
  "KHC",
  "KO",
  "LLY",
  "LMT",
  "LOW",
  "MA",
  "MCD",
  "MDLZ",
  "META",
  "MMC",
  "MMM",
  "MNST",
  "MO",
  "MPC",
  "MRK",
  "MS",
  "MSFT",
  "NEE",
  "NFLX",
  "NKE",
  "NOC",
  "NOW",
  "NSC",
  "NVDA",
  "NWSA",
  "ORCL",
  "OXY",
  "PEG",
  "PEP",
  "PFE",
  "PG",
  "PGR",
  "PH",
  "PM",
  "PSX",
  "QCOM",
  "REGN",
  "RTX",
  "SBUX",
  "SCHW",
  "SLB",
  "SO",
  "SPGI",
  "SRE",
  "SYK",
  "T",
  "TFC",
  "TGT",
  "TJX",
  "TMO",
  "TMUS",
  "TSLA",
  "TXN",
  "UNH",
  "UNP",
  "UPS",
  "USB",
  "V",
  "VLO",
  "VRTX",
  "VZ",
  "WBD",
  "WFC",
  "WMT",
  "XEL",
  "XOM",
].sort()

// Helper function to get the numerical limit for top ranked stocks
export const getTopRankedValue = (percentage: number): number => {
  if (percentage <= 16) return 500 // Top 500
  if (percentage <= 50) return 100 // Top 100
  if (percentage <= 83) return 50 // Top 50
  return 10 // Top 10
}

// Helper function to get the label for top ranked stocks
export const getTopRankedLabel = (percentage: number): string => {
  if (percentage <= 16) return "Top 500"
  if (percentage <= 50) return "Top 100"
  if (percentage <= 83) return "Top 50"
  return "Top 10"
}

// Shared 12-stop market-cap ladder for the Step 2 pre-filter slider.
// Keep values and labels in lockstep — indexed together by preFilterMarketCap[0].
export const PRE_FILTER_MARKET_CAP_TIERS = [
  { value: 0, label: "Any" },
  { value: 100_000_000, label: "$100M+" },
  { value: 300_000_000, label: "$300M+" },
  { value: 500_000_000, label: "$500M+" },
  { value: 1_000_000_000, label: "$1B+" },
  { value: 2_000_000_000, label: "$2B+" },
  { value: 5_000_000_000, label: "$5B+" },
  { value: 10_000_000_000, label: "$10B+" },
  { value: 25_000_000_000, label: "$25B+" },
  { value: 50_000_000_000, label: "$50B+" },
  { value: 100_000_000_000, label: "$100B+" },
  { value: 250_000_000_000, label: "$250B+" },
] as const

// Step 2 volatility (premium-richness) ladder. Values are minimum daily
// range % ((high − low) / close) from Polygon grouped bars — a free realized-
// volatility proxy that tracks implied volatility (and therefore option
// premium) closely. 0 = no filter.
export const PRE_FILTER_VOLATILITY_TIERS = [
  { value: 0, label: "Any" },
  { value: 2, label: "2%+" },
  { value: 3, label: "3%+" },
  { value: 4, label: "4%+" },
  { value: 5, label: "5%+" },
  { value: 7, label: "7%+" },
  { value: 10, label: "10%+" },
] as const
